#!/usr/bin/env python3

import argparse

from base64 import b64encode, b64decode

from fcmp import fcmp_keygen, fcmp_encrypt, fcmp_decrypt

DESCRIPTION = "Fast Cipher Message Protocol 1.0"

FILENAME_HELP = "File to encrypt/decrypt"
KEYGEN_HELP = "Generate new FCMP keys"
KEY_HELP = "Choosing a path for keys"
ENCRYPT_HELP = "Encrypt file with public_key"

def args():
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument("filename", metavar="filename", type=str, help=FILENAME_HELP)
    parser.add_argument("-kg", metavar="\b", help=KEYGEN_HELP)
    parser.add_argument("-k", metavar="path", type=str, help=KEY_HELP)
    parser.add_argument("-e", metavar="public_key", type=str, help=ENCRYPT_HELP)

    return parser.parse_args()

def main():
    args()
    exit(0)

if __name__ == "__main__":
    main()
